import { ComplianceItem, ProfileState, ExposureMatrix } from '../types';

export const MASTER_STATUTORY_CATALOG: Omit<ComplianceItem, 'isApplicable' | 'userStatus'>[] = [
  // --- PHASE 1: PRE-INCORPORATION & DAY-0 ZERO-TOLERANCE ---
  {
    id: 'mca_dsc',
    title: 'Class 3 Digital Signature Certificate (DSC)',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Legal Identity',
    statutoryAuthority: 'Controller of Certifying Authorities (CCA)',
    governingAct: 'Information Technology Act, 2000 (Section 35)',
    obligationType: 'Mandatory',
    turnaroundTime: '1–2 Business Days',
    turnaroundDays: 2,
    govtFee: 1500,
    professionalFee: 1000,
    penaltyRisk: 'Zero-tolerance blocker: Inability to execute MCA portal filings or sign statutory documents.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://cca.gov.in',
    portalName: 'CCA Official Portal',
    summary: 'Cryptographic USB token hardware key required for all prospective directors and designated partners to digitally sign statutory incorporation forms on the MCA V3 portal.',
    prerequisites: ['Director Aadhaar with OTP mobile link', 'Director PAN card', 'Passport-size photograph'],
    checklist: ['e-KYC biometric/OTP verification', 'Video recording verification', 'Token issuance and driver installation'],
    triggersSummary: 'Mandatory for all incorporated entities (Pvt Ltd, LLP, Public Ltd, OPC).',
  },
  {
    id: 'mca_name_approval',
    title: 'RUN / SPICe+ Part A Name Reservation',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Corporate Identity',
    statutoryAuthority: 'Ministry of Corporate Affairs (Central Registration Centre)',
    governingAct: 'Companies Act, 2013 (Section 4) / LLP Act, 2008',
    obligationType: 'Mandatory',
    turnaroundTime: '2–3 Business Days',
    turnaroundDays: 3,
    govtFee: 1000,
    professionalFee: 2500,
    penaltyRisk: 'Rejection or trademark infringement notice; loss of non-refundable filing fee.',
    penaltySeverity: 'Medium',
    portalUrl: 'https://www.mca.gov.in',
    portalName: 'MCA V3 Portal',
    summary: 'Formal reservation of the corporate legal name ensuring distinctiveness, non-infringement of registered trademarks, and alignment with the charter objectives.',
    prerequisites: ['Proposed 2 unique name choices', 'Main business objects summary', 'Trademark search clearance (IPIndia)'],
    checklist: ['IPIndia class search report', 'Board resolution if subsidiary or identical wordmark', 'SPICe+ Part A submission'],
    triggersSummary: 'Mandatory for corporate entities prior to charter drafting.',
  },
  {
    id: 'mca_incorporation_spice',
    title: 'SPICe+ Part B Incorporation, MoA & AoA Charter',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Corporate Constitution',
    statutoryAuthority: 'Registrar of Companies (ROC) & MCA',
    governingAct: 'Companies Act, 2013 (Section 7) / LLP Act, 2008 (Form FiLLiP)',
    obligationType: 'Mandatory',
    turnaroundTime: '4–6 Business Days',
    turnaroundDays: 5,
    govtFee: 3500,
    professionalFee: 9000,
    penaltyRisk: 'Illegal corporate representation; personal liability for promoters on pre-incorporation contracts.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.mca.gov.in',
    portalName: 'MCA V3 Portal',
    summary: 'Master electronic filing encompassing electronic Memorandum of Association (eMoA), Articles of Association (eAoA), Director DIN generation, Registered Office declaration, and Certificate of Incorporation (INC-11).',
    prerequisites: ['Approved Name Reservation', 'Registered office lease agreement + Owner NOC', 'Utility bill (< 60 days old)', 'Director consent forms (DIR-2)'],
    checklist: ['Execution of eMoA & eAoA with digital signatures', 'Declaration by professional (CA/CS in Form INC-8)', 'Verification of registered address premises'],
    triggersSummary: 'Fundamental statutory requirement for corporate legal existence.',
  },
  {
    id: 'it_pan_tan',
    title: 'Corporate Permanent Account Number (PAN) & TAN',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Direct Taxation',
    statutoryAuthority: 'Central Board of Direct Taxes (CBDT)',
    governingAct: 'Income Tax Act, 1961 (Section 139A & 203A)',
    obligationType: 'Mandatory',
    turnaroundTime: 'Simultaneous with SPICe+ (1 Day)',
    turnaroundDays: 1,
    govtFee: 150,
    professionalFee: 500,
    penaltyRisk: '₹10,000 penalty under Section 272B for failure to obtain/quote PAN; unable to open bank current accounts.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://incometax.gov.in',
    portalName: 'Income Tax e-Filing Portal',
    summary: '10-digit alphanumeric permanent identification for corporate direct tax obligations, corporate banking, and Tax Deduction at Source (TDS) withholding registration.',
    prerequisites: ['Certificate of Incorporation or Partnership Deed', 'Authorized Signatory Proof'],
    checklist: ['Verification on NSDL/UTIITSL database', 'Direct delivery of physical and e-PAN card', 'TAN allotment for TDS compliance'],
    triggersSummary: 'Mandatory for all business identities regardless of turnover.',
  },
  {
    id: 'mca_commencement_inc20a',
    title: 'Declaration of Commencement of Business (Form INC-20A)',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Corporate Governance',
    statutoryAuthority: 'Registrar of Companies (ROC)',
    governingAct: 'Companies Act, 2013 (Section 10A)',
    obligationType: 'Mandatory',
    turnaroundTime: '180 Days statutory window (Processed in 2 Days)',
    turnaroundDays: 2,
    govtFee: 500,
    professionalFee: 2000,
    penaltyRisk: 'Company fine of ₹50,000 + ₹1,000/day for each director; ROC strike-off of company name from register.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.mca.gov.in',
    portalName: 'MCA V3 Portal',
    summary: 'Mandatory electronic declaration by directors verifying that each subscriber to the memorandum has paid the value of shares agreed to be taken into the corporate current account.',
    prerequisites: ['Current account operationalized', 'Proof of share capital credit into bank statement', 'Board resolution noting share capital receipt'],
    checklist: ['Bank bank statement showing subscriber credits', 'Certification by practicing Chartered Accountant / CS', 'INC-20A filing before entering commercial contracts'],
    triggersSummary: 'Mandatory for Private Limited and Public Limited companies incorporated under Companies Act 2013.',
  },
  {
    id: 'mca_first_auditor_adt1',
    title: 'First Statutory Auditor Appointment (Form ADT-1)',
    phase: 1,
    phaseLabel: 'Phase 1: Pre-Incorporation',
    category: 'Statutory Audit',
    statutoryAuthority: 'Ministry of Corporate Affairs',
    governingAct: 'Companies Act, 2013 (Section 139(6))',
    obligationType: 'Mandatory',
    turnaroundTime: 'Within 30 Days of Incorporation',
    turnaroundDays: 2,
    govtFee: 600,
    professionalFee: 1500,
    penaltyRisk: 'Fine on company up to ₹5,00,000 and default on annual accounts certification.',
    penaltySeverity: 'High',
    portalUrl: 'https://www.mca.gov.in',
    portalName: 'MCA V3 Portal',
    summary: 'The Board of Directors must appoint the company’s first statutory auditor within 30 days of registration to hold office until the conclusion of the first Annual General Meeting.',
    prerequisites: ['Written consent and eligibility certificate from practicing CA firm', 'Board resolution copy'],
    checklist: ['Form ADT-1 filing with ROC', 'Auditor eligibility confirmation under Section 141', 'Engagement letter execution'],
    triggersSummary: 'Mandatory for all incorporated entities with audited accounts requirements.',
  },

  // --- PHASE 2: OPERATIONAL CLEARANCES ---
  {
    id: 'state_shop_establishment',
    title: 'State Shop & Commercial Establishment Registration',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Labour & Premises',
    statutoryAuthority: 'State Department of Labour / Municipal Corporation',
    governingAct: 'State Shops & Establishments Act (e.g. Maharashtra Gumasta)',
    obligationType: 'Mandatory',
    turnaroundTime: '3–7 Business Days',
    turnaroundDays: 5,
    govtFee: 1200,
    professionalFee: 2500,
    penaltyRisk: 'Closure of commercial premises; municipal compounding fines up to ₹25,000 + ₹200/day.',
    penaltySeverity: 'High',
    portalUrl: 'https://lms.mahaonline.gov.in',
    portalName: 'State Labour Department',
    summary: 'Primary operational license regulating conditions of work, working hours, statutory holidays, wage payments, and health standards for commercial offices, stores, and warehouses.',
    prerequisites: ['Registered lease deed / ownership deed', 'Premises exterior photo with company name signage', 'PAN & Incorporation Certificate'],
    checklist: ['Application on State Labour portal', 'Listing of employees and working hours', 'Certificate download and physical display at premise entrance'],
    triggersSummary: 'Mandatory for all business entities operating out of a physical or commercial premise.',
  },
  {
    id: 'trade_license_municipal',
    title: 'Municipal Health & Trade License',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Municipal & Health',
    statutoryAuthority: 'Local Urban Local Body / Municipal Corporation (e.g. BMC, BBMP, MCD)',
    governingAct: 'State Municipal Corporation Acts (e.g. MMC Act Section 394)',
    obligationType: 'Conditional',
    turnaroundTime: '10–20 Business Days',
    turnaroundDays: 15,
    govtFee: 6500,
    professionalFee: 5000,
    penaltyRisk: 'Premises sealing by Municipal Health Officer; confiscation of commercial equipment.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://portal.mcgm.gov.in',
    portalName: 'Municipal Corporation Portal',
    summary: 'Municipal sanitary clearance verifying that the commercial operation poses no public health hazard, environmental nuisance, or zoning law violation.',
    prerequisites: ['Sanctioned layout plan', 'Fire safety compliance certificate', 'Shop & Establishment certificate'],
    checklist: ['Premises site inspection by Municipal Sanitary Inspector', 'NOC from property tax department', 'Display of annual trade license number'],
    triggersSummary: 'Mandatory for physical F&B, hospitality, retail storefronts, and manufacturing units.',
  },
  {
    id: 'fssai_license',
    title: 'FSSAI Food Safety License / Registration',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Food Safety',
    statutoryAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    governingAct: 'Food Safety and Standards Act, 2006',
    obligationType: 'Mandatory',
    turnaroundTime: '7–15 Business Days',
    turnaroundDays: 10,
    govtFee: 5000,
    professionalFee: 4000,
    penaltyRisk: 'Carrying on food business without license: Imprisonment up to 6 months and fine up to ₹5,00,000 (Section 63).',
    penaltySeverity: 'Critical',
    portalUrl: 'https://foscos.fssai.gov.in',
    portalName: 'FSSAI FoSCoS Portal',
    summary: 'Statutory 14-digit license number required for any entity manufacturing, processing, packaging, storing, distributing, or retailing food products or dietary supplements.',
    prerequisites: ['Kitchen layout / processing flow chart', 'Medical fitness certificates of food handlers', 'Water test report (potability) from NABL lab', 'Equipment list'],
    checklist: ['FoSCoS application submission', 'Designation of Food Safety Supervisor (FoSTaC)', '14-digit FSSAI number print on all packaging and bills'],
    triggersSummary: 'Mandatory for F&B, Cloud Kitchens, Restaurants, Food Aggregators, and Packaged Food Retailers.',
  },
  {
    id: 'fire_safety_noc',
    title: 'Fire Safety Clearance & NOC',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Public Safety',
    statutoryAuthority: 'Directorate of Fire Prevention Services',
    governingAct: 'National Building Code (Part 4) & State Fire Safety Acts',
    obligationType: 'Conditional',
    turnaroundTime: '15–30 Business Days',
    turnaroundDays: 20,
    govtFee: 8000,
    professionalFee: 6500,
    penaltyRisk: 'Immediate notice of premise eviction, disconnection of water/electricity supply, criminal negligence liability.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://nfs.gov.in',
    portalName: 'Fire Services Directorate',
    summary: 'Inspection and certification that premises are equipped with adequate emergency egress routes, hydrants, smoke detectors, and fire suppression systems.',
    prerequisites: ['Architect-certified floor egress plan', 'Fire extinguisher installation invoices', 'Building occupancy certificate'],
    checklist: ['Site inspection by Fire Station Officer', 'Mock fire drill compliance log', 'Annual Form B renewal submission'],
    triggersSummary: 'Mandatory for physical restaurants, industrial factories, and commercial offices with occupant load > 50.',
  },
  {
    id: 'pollution_control_cto',
    title: 'SPCB Consent to Establish (CTE) & Consent to Operate (CTO)',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Environmental Protection',
    statutoryAuthority: 'State Pollution Control Board (SPCB) & CPCB',
    governingAct: 'Water (Prevention and Control of Pollution) Act 1974 & Air Act 1981',
    obligationType: 'Conditional',
    turnaroundTime: '25–45 Business Days',
    turnaroundDays: 30,
    govtFee: 12000,
    professionalFee: 15000,
    penaltyRisk: 'Closure orders under Section 31A of Air Act / Section 33A of Water Act; penalties up to ₹1,00,000 + criminal charges.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://cpcb.nic.in',
    portalName: 'Central / State Pollution Control Board',
    summary: 'Statutory environmental clearance categorized by White/Green/Orange/Red industrial classifications, regulating effluent discharge, emissions, and hazardous waste disposal.',
    prerequisites: ['Project report with material balance', 'Effluent Treatment Plant (ETP) / STP layout plan', 'Diesel Generator (DG) set acoustic enclosure details'],
    checklist: ['Online OCMMS portal filing', 'Pollution Control Inspector premise assessment', 'Environmental statement Form V submission'],
    triggersSummary: 'Mandatory for manufacturing plants, commercial cloud kitchens with grease traps, and healthcare diagnostic labs.',
  },
  {
    id: 'legal_metrology_packaging',
    title: 'Legal Metrology Packaged Commodities Registration',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Consumer Protection',
    statutoryAuthority: 'Department of Consumer Affairs (Legal Metrology Division)',
    governingAct: 'Legal Metrology (Packaged Commodities) Rules, 2011 (Rule 27)',
    obligationType: 'Conditional',
    turnaroundTime: '7–12 Business Days',
    turnaroundDays: 10,
    govtFee: 2500,
    professionalFee: 3500,
    penaltyRisk: 'Seizure of goods from warehouses and retail shelves; fine of ₹25,000 per director for non-compliant declarations.',
    penaltySeverity: 'High',
    portalUrl: 'https://consumeraffairs.nic.in',
    portalName: 'National Legal Metrology Portal',
    summary: 'Mandatory registration of manufacturer, packer, or importer required before pre-packaged commodities are distributed or listed on e-commerce marketplaces.',
    prerequisites: ['Specimen packaging label with MRP, net quantity, batch number, customer care details', 'Shop/Factory license'],
    checklist: ['Verification of metric unit fonts and sizes on primary artwork', 'Filing under Rule 27', 'E-commerce listing compliance audit'],
    triggersSummary: 'Mandatory for Retail, E-Commerce, and Consumer Goods packaging.',
  },
  {
    id: 'clinical_est_license',
    title: 'Clinical Establishments Registration & Bio-Medical Waste Authorization',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Healthcare Governance',
    statutoryAuthority: 'State Health Authority & Pollution Control Board',
    governingAct: 'Clinical Establishments (Registration and Regulation) Act, 2010',
    obligationType: 'Conditional',
    turnaroundTime: '20–35 Business Days',
    turnaroundDays: 25,
    govtFee: 15000,
    professionalFee: 12000,
    penaltyRisk: 'Illegal practice prosecution; immediate closure; fine of ₹50,000 for first violation, ₹5,00,000 for repeat.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://clinicalestablishments.gov.in',
    portalName: 'National Clinical Registry',
    summary: 'Licensing of diagnostic centers, clinics, and health-tech facilities with mandatory tie-up with Common Bio-Medical Waste Treatment Facilities (CBMWTF).',
    prerequisites: ['Medical director credentials & state medical council registration', 'Premises sanitation certificate', 'Waste management contract'],
    checklist: ['Bar-coded bio-medical waste tracking log', 'Form IV bio-medical waste authorization', 'Periodic radiation safety clearance if X-Ray/CT used'],
    triggersSummary: 'Mandatory for Healthcare, Diagnostics, and Tele-medicine physical clinics.',
  },
  {
    id: 'fintech_rbi_authorization',
    title: 'RBI Payment Aggregator / In-Principle Authorization & CKYC',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Financial Regulation',
    statutoryAuthority: 'Reserve Bank of India (Department of Payment and Settlement Systems)',
    governingAct: 'Payment and Settlement Systems Act, 2007 / PMLA 2002',
    obligationType: 'Conditional',
    turnaroundTime: '60–120 Business Days',
    turnaroundDays: 90,
    govtFee: 25000,
    professionalFee: 65000,
    penaltyRisk: 'Criminal prosecution under Banking Regulation Act; freezing of nodal/escrow settlement accounts.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://rbi.org.in',
    portalName: 'RBI Official Portal',
    summary: 'Statutory net-worth certification (₹15 Cr initial, ₹25 Cr ongoing) and security architecture audit (ISO 27001 / SAR) required for fintech payment routing and escrow management.',
    prerequisites: ['Net-worth certificate by Statutory Auditor', 'System Audit Report (SAR) by CERT-In empaneled auditor', 'Board approved PMLA KYC policy'],
    checklist: ['RBI DPSS in-principle application', 'Escrow account agreement with scheduled commercial bank', 'FIU-IND reporting officer registration'],
    triggersSummary: 'Mandatory for Fintech platforms, neo-banks, and digital payment intermediaries.',
  },

  // --- PHASE 3: HEADCOUNT & SOCIAL SECURITY ---
  {
    id: 'labour_esic',
    title: 'ESIC Statutory Registration & Monthly Remittance',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'Social Security',
    statutoryAuthority: "Employees' State Insurance Corporation (ESIC)",
    governingAct: "Employees' State Insurance Act, 1948",
    obligationType: 'Mandatory',
    turnaroundTime: '2–4 Business Days',
    turnaroundDays: 3,
    govtFee: 0,
    professionalFee: 2500,
    penaltyRisk: 'Imprisonment up to 3 years and ₹10,000 fine for default in contribution remittance (Section 85); 12% annual interest on delayed funds.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.esic.gov.in',
    portalName: 'ESIC Shram Suvidha Portal',
    summary: 'Comprehensive social security and health insurance coverage for all non-seasonal employees earning gross monthly wages up to ₹21,000 (₹25,000 for persons with disabilities). Employer contributes 3.25%, employee 0.75%.',
    prerequisites: ['Entity PAN & Incorporation certificate', 'Employee master data with Aadhaar and family details', 'Bank cancelled cheque'],
    checklist: ['17-digit Employer Code generation via Shram Suvidha', 'Biometric Pehchan card facilitation', 'Monthly return and challan payment by 15th of succeeding month'],
    triggersSummary: 'Mandatory when organization headcount reaches 10 or more employees (in implemented states/sectors).',
  },
  {
    id: 'labour_epfo',
    title: 'EPFO Registration & Universal Provident Fund Compliance',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'Social Security',
    statutoryAuthority: "Employees' Provident Fund Organisation (EPFO)",
    governingAct: "Employees' Provident Funds and Miscellaneous Provisions Act, 1952",
    obligationType: 'Mandatory',
    turnaroundTime: '2–4 Business Days',
    turnaroundDays: 3,
    govtFee: 0,
    professionalFee: 3000,
    penaltyRisk: 'Damages under Section 14B up to 25% of arrears, interest under Section 7Q at 12% p.a., attachment of corporate bank accounts.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.epfindia.gov.in',
    portalName: 'EPFO Unified Portal',
    summary: 'Statutory retirement savings scheme mandatory for establishments employing 20 or more persons. Employer contributes 12% (3.67% EPF + 8.33% EPS) and employee contributes matching 12% on basic + DA (wage ceiling ₹15,000/mo or voluntary on actuals).',
    prerequisites: ['Digital Signature Certificate of Authorized Signatory', 'Salary structure breakdown (Basic, HRA, DA)', 'List of all active employees with UAN'],
    checklist: ['Establishment registration code generation', 'UAN allotment and Aadhaar seeding for new joiners', 'Electronic Challan cum Return (ECR) filing by 15th of each month'],
    triggersSummary: 'Mandatory statutory threshold upon reaching 20+ headcount.',
  },
  {
    id: 'state_ptax',
    title: 'Professional Tax Enrolment (PTEC) & Registration (PTRC)',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'State Direct Tax',
    statutoryAuthority: 'State Department of Goods and Services Tax / Commercial Taxes',
    governingAct: 'State Tax on Professions, Trades, Callings and Employments Acts',
    obligationType: 'Mandatory',
    turnaroundTime: '3–5 Business Days',
    turnaroundDays: 4,
    govtFee: 2500,
    professionalFee: 2000,
    penaltyRisk: '10% penalty on unpaid tax + 1.25% monthly compounding interest; personal liability of directors.',
    penaltySeverity: 'Medium',
    portalUrl: 'https://www.mahagst.gov.in',
    portalName: 'State Commercial Tax Portal',
    summary: 'Dual statutory registration: PTEC (for the company/directors to pay corporate tax, typically ₹2,500/year) and PTRC (to deduct state professional tax up to ₹200–₹300/month from employee salaries and remit to the state treasury).',
    prerequisites: ['Salary registers showing employee state allocations', 'Bank current account details', 'Registered office proof'],
    checklist: ['Dual certificate issuance: PTEC & PTRC numbers', 'Monthly/Quarterly PTRC return filing based on liability', 'Annual Form III-B summary reconciliation'],
    triggersSummary: 'Mandatory for all business employers in notified states (Maharashtra, Karnataka, Gujarat, Tamil Nadu, Telangana, etc.).',
  },
  {
    id: 'posh_internal_committee',
    title: 'POSH Act Internal Committee (IC) & Statutory Annual Filing',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'Workplace Governance',
    statutoryAuthority: 'Ministry of Women and Child Development & District Local Officer',
    governingAct: 'Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013',
    obligationType: 'Mandatory',
    turnaroundTime: '5–7 Business Days',
    turnaroundDays: 6,
    govtFee: 0,
    professionalFee: 6000,
    penaltyRisk: '₹50,000 fine for first offense; cancellation/non-renewal of business licenses on subsequent conviction.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://wcd.nic.in',
    portalName: 'Ministry of Women & Child Development',
    summary: 'Mandatory constitution of an Internal Committee (Presiding Officer woman, min 2 employee members, 1 independent external NGO member) at every administrative location. Obligation to publish policy and file Annual POSH Report with District Collector.',
    prerequisites: ['Formal Board Resolution adopting POSH Policy', 'Selection of eligible Presiding Officer and external legal member'],
    checklist: ['Internal Complaints Committee formal constitution order', 'Employee sensitization workshop documentation', 'Filing of Annual Report with District Officer by January 31st', 'Disclosure in Directors’ Report (MCA AOC-4)'],
    triggersSummary: 'Mandatory for all establishments with 10 or more employees (strictly enforced at 50+).',
  },
  {
    id: 'gratuity_trust_setup',
    title: 'Payment of Gratuity Act Compliance & Group Trust Creation',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'Employee Benefits',
    statutoryAuthority: 'Controlling Authority under Payment of Gratuity Act / Ministry of Labour',
    governingAct: 'Payment of Gratuity Act, 1972',
    obligationType: 'Mandatory',
    turnaroundTime: '7–14 Business Days',
    turnaroundDays: 10,
    govtFee: 0,
    professionalFee: 5000,
    penaltyRisk: 'Imprisonment up to 2 years and recovery with 10% statutory interest for non-payment or failure to insure.',
    penaltySeverity: 'High',
    portalUrl: 'https://labour.gov.in',
    portalName: 'Ministry of Labour & Employment',
    summary: 'Statutory entitlement payable to employees completing 5 continuous years of service (15 days last drawn salary per completed year). Mandatory institutional gratuity group insurance or approved irrevocable gratuity trust.',
    prerequisites: ['Actuarial valuation report (AS-15 / Ind AS 19)', 'Group gratuity insurance policy tie-up (LIC / Private Life Insurers)'],
    checklist: ['Notice of Opening in Form A to Controlling Authority', 'Execution of Gratuity Trust Deed and Rules', 'Annual actuarial contribution provisioning'],
    triggersSummary: 'Mandatory upon employing 10 or more persons.',
  },
  {
    id: 'creche_facility_mandate',
    title: 'Statutory Crèche Facility & Maternity Benefit Infrastructure',
    phase: 3,
    phaseLabel: 'Phase 3: Headcount & Social Security',
    category: 'Maternity Welfare',
    statutoryAuthority: 'Chief Inspector of Factories / State Labour Commissioner',
    governingAct: 'Maternity Benefit (Amendment) Act, 2017 (Section 11A)',
    obligationType: 'Conditional',
    turnaroundTime: '15–30 Days',
    turnaroundDays: 20,
    govtFee: 0,
    professionalFee: 4000,
    penaltyRisk: 'Labour court prosecution of directors; financial penalty up to ₹50,000.',
    penaltySeverity: 'Medium',
    portalUrl: 'https://labour.gov.in',
    portalName: 'State Labour Department',
    summary: 'Mandatory provision of a crèche facility within the workplace premises or within a 500-meter radius, permitting 4 daily mother visits, for every establishment employing 50 or more employees.',
    prerequisites: ['On-site dedicated crèche room or tie-up with licensed neighborhood childcare provider', 'Child-safety protocols'],
    checklist: ['Execution of shared crèche service level agreement', 'Written notification to all female joiners regarding crèche benefits', 'Maintenance of crèche inspection log'],
    triggersSummary: 'Triggered when headcount exceeds 50 personnel.',
  },

  // --- PHASE 4: RECURRING GOVERNANCE & TAX FILINGS ---
  {
    id: 'tax_gst_registration',
    title: 'Goods and Services Tax (GST) Registration (Form GST REG-01)',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Indirect Taxation',
    statutoryAuthority: 'Goods and Services Tax Network (GSTN) & CBIC',
    governingAct: 'Central Goods and Services Tax Act, 2017 (Section 22 & 24)',
    obligationType: 'Mandatory',
    turnaroundTime: '3–7 Business Days',
    turnaroundDays: 5,
    govtFee: 0,
    professionalFee: 2500,
    penaltyRisk: '100% tax evaded or ₹10,000 (whichever is higher) under Section 122; input tax credit blocked; buyer invoices invalidated.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.gst.gov.in',
    portalName: 'GST Common Portal',
    summary: '15-digit GSTIN allotment required for taxable supply of goods exceeding ₹40L (₹20L in special category states) or services exceeding ₹20L, OR mandatory from Day-1 for interstate supply, e-commerce, or export.',
    prerequisites: ['Premises ownership proof / registered lease + electricity bill', 'Director photo and Aadhaar biometric linkage', 'Bank account cancelled cheque'],
    checklist: ['Filing of Form GST REG-01', 'Aadhaar authentication via mobile OTP or biometric kiosk', 'Display of GSTIN on trade signboard at principal place of business'],
    triggersSummary: 'Triggered by revenue threshold > ₹20L/₹40L, or interstate supplies, or cross-border exports.',
  },
  {
    id: 'tax_gst_returns',
    title: 'Monthly / Quarterly GST Return Filings (GSTR-1 & GSTR-3B)',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Indirect Taxation',
    statutoryAuthority: 'CBIC / GSTN',
    governingAct: 'CGST Act, 2017 (Section 37 & 39)',
    obligationType: 'Mandatory',
    turnaroundTime: '11th & 20th of every month',
    turnaroundDays: 1,
    govtFee: 0,
    professionalFee: 3000,
    penaltyRisk: 'Late fee ₹50/day (₹20/day for NIL) capped at ₹5,000/return; 18% annual interest on unpaid tax; e-way bill blocking after 2 missed returns.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.gst.gov.in',
    portalName: 'GST Portal',
    summary: 'Continuous compliance mechanism: GSTR-1 (outward invoice supplies) by the 11th, and GSTR-3B (summary return and tax payment) by the 20th of each succeeding month.',
    prerequisites: ['Sales invoice registers with HSN/SAC codes', 'Purchase registers for GSTR-2B ITC matching'],
    checklist: ['Reconciliation of electronic credit ledger', 'Offsetting of CGST, SGST, IGST liability', 'Verification with DSC / EVC'],
    triggersSummary: 'Mandatory recurring requirement for all GST-registered businesses.',
  },
  {
    id: 'tax_gst_lut_export',
    title: 'Letter of Undertaking (LUT) for Zero-Rated Exports (GST RFD-11)',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Export Compliance',
    statutoryAuthority: 'CBIC / GSTN',
    governingAct: 'IGST Act, 2017 (Section 16)',
    obligationType: 'Conditional',
    turnaroundTime: '1–2 Business Days (Annual Renewal)',
    turnaroundDays: 2,
    govtFee: 0,
    professionalFee: 1500,
    penaltyRisk: 'Forced payment of 18% IGST on all export billings, locking working capital in prolonged government refund cycles.',
    penaltySeverity: 'High',
    portalUrl: 'https://www.gst.gov.in',
    portalName: 'GST Portal',
    summary: 'Annual electronic bond enabling exporters of services (e.g. SaaS) and physical goods to export at 0% GST without payment of upfront Integrated GST, preserving operating capital.',
    prerequisites: ['Active GSTIN', 'Two independent witnesses with PAN and address'],
    checklist: ['Form GST RFD-11 annual filing at start of fiscal year (April 1)', 'Quoting LUT ARN on all commercial export invoices', 'Realization of foreign currency within 9 months'],
    triggersSummary: 'Mandatory for SaaS, tech exporters, and cross-border businesses.',
  },
  {
    id: 'tax_advance_tax',
    title: 'Statutory Advance Tax Instalments (Sections 208–211)',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Direct Taxation',
    statutoryAuthority: 'Central Board of Direct Taxes (CBDT)',
    governingAct: 'Income Tax Act, 1961 (Sections 208, 209, 210, 211, 234B, 234C)',
    obligationType: 'Mandatory',
    turnaroundTime: 'Quarterly (Jun 15, Sep 15, Dec 15, Mar 15)',
    turnaroundDays: 1,
    govtFee: 0,
    professionalFee: 2000,
    penaltyRisk: 'Mandatory 1% per month statutory interest under Section 234C (deferment) and Section 234B (shortfall).',
    penaltySeverity: 'Medium',
    portalUrl: 'https://eportal.incometax.gov.in',
    portalName: 'Income Tax e-Filing Portal',
    summary: 'Pay-as-you-earn corporate income tax requirement if estimated annual tax liability exceeds ₹10,000. Staged instalments: 15% by June 15, 45% by Sept 15, 75% by Dec 15, and 100% by March 15.',
    prerequisites: ['Quarterly P&L calculation', 'Estimated full-year corporate taxable profit statement'],
    checklist: ['Challan ITNS 280 generation on e-filing portal', 'Credit verification in AIS / Form 26AS', 'Rebalancing projected income tax computations quarterly'],
    triggersSummary: 'Mandatory for all profit-generating businesses exceeding ₹10,000 annual tax liability.',
  },
  {
    id: 'tax_section_44ab_audit',
    title: 'Mandatory Tax Audit under Section 44AB & Form 3CD',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Statutory Audit',
    statutoryAuthority: 'Income Tax Department (CBDT)',
    governingAct: 'Income Tax Act, 1961 (Section 44AB)',
    obligationType: 'Conditional',
    turnaroundTime: 'Due by September 30 annually',
    turnaroundDays: 15,
    govtFee: 0,
    professionalFee: 25000,
    penaltyRisk: 'Penalty under Section 271B equal to 0.5% of total sales/turnover or ₹1,50,000 (whichever is lower).',
    penaltySeverity: 'Critical',
    portalUrl: 'https://incometax.gov.in',
    portalName: 'Income Tax e-Filing Portal',
    summary: 'Comprehensive examination of books of account by an independent Chartered Accountant to ensure compliance with tax provisions and deductions. Form 3CA/3CB and comprehensive statement of particulars in Form 3CD.',
    prerequisites: ['Audited Balance Sheet and Profit & Loss Account', 'Depreciation schedule, related party disclosures, TDS matching'],
    checklist: ['Appointment of Tax Auditor', 'Filing of Form 3CA/3CD on e-filing portal by CA', 'Acceptance by company director before statutory due date'],
    triggersSummary: 'Mandatory when business turnover exceeds ₹1.5 Cr (or ₹10 Cr if cash transactions are under 5%).',
  },
  {
    id: 'mca_annual_filings',
    title: 'Annual ROC Governance Filings (Form AOC-4, MGT-7 & DIR-3 KYC)',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Corporate Governance',
    statutoryAuthority: 'Ministry of Corporate Affairs',
    governingAct: 'Companies Act, 2013 (Sections 92, 137) / LLP Form 8 & 11',
    obligationType: 'Mandatory',
    turnaroundTime: 'Annual (Oct 30 / Nov 29)',
    turnaroundDays: 5,
    govtFee: 1200,
    professionalFee: 8000,
    penaltyRisk: 'Compounding additional fee of ₹100 per day without upper limit; director DIN deactivation; prosecution of officers in default.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.mca.gov.in',
    portalName: 'MCA V3 Portal',
    summary: 'Statutory annual disclosures: Form AOC-4 (Financial statements, Auditor Report, Board Report within 30 days of AGM), Form MGT-7 (Annual return within 60 days of AGM), and annual DIR-3 KYC verification for every active director.',
    prerequisites: ['Adoption of audited financial accounts at Annual General Meeting', 'Signed Directors’ Report and Secretarial Disclosures'],
    checklist: ['XBRL / Non-XBRL filing of Balance Sheet in AOC-4', 'Filing of shareholding pattern in MGT-7', 'DIR-3 KYC web-verification for all DIN holders by Sept 30'],
    triggersSummary: 'Mandatory annual requirement for all incorporated companies and LLPs.',
  },
  {
    id: 'trade_iec_dgft',
    title: 'Import Export Code (IEC) from DGFT',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Foreign Trade',
    statutoryAuthority: 'Directorate General of Foreign Trade (DGFT) & Ministry of Commerce',
    governingAct: 'Foreign Trade (Development and Regulation) Act, 1992',
    obligationType: 'Conditional',
    turnaroundTime: '1–3 Business Days',
    turnaroundDays: 2,
    govtFee: 500,
    professionalFee: 2000,
    penaltyRisk: 'Customs port confiscation of imported cargo; inability to clear outward export consignments through ICEGATE.',
    penaltySeverity: 'High',
    portalUrl: 'https://www.dgft.gov.in',
    portalName: 'DGFT Unified Portal',
    summary: '10-digit national identifier mandatory for commercial import or export of goods and designated services, linked directly to entity PAN.',
    prerequisites: ['Entity PAN card', 'Bank certificate or cancelled cheque in business name', 'Registered office address proof'],
    checklist: ['Online DGFT portal submission', 'Annual electronic profile verification (April–June window)', 'ICEGATE customs port registration linkage'],
    triggersSummary: 'Mandatory for businesses engaged in cross-border trade, importing goods, or exporting hardware/products.',
  },
  {
    id: 'fema_softex_reporting',
    title: 'FEMA SOFTEX Form Filing & RBI Export Reporting',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Foreign Exchange',
    statutoryAuthority: 'Reserve Bank of India & Software Technology Parks of India (STPI)',
    governingAct: 'Foreign Exchange Management (Export of Goods & Services) Regulations, 2016',
    obligationType: 'Conditional',
    turnaroundTime: 'Within 30 days of export invoice',
    turnaroundDays: 3,
    govtFee: 1000,
    professionalFee: 4000,
    penaltyRisk: 'FEMA compounding penalty up to thrice the sum involved; regulatory scrutiny on foreign currency inflows.',
    penaltySeverity: 'High',
    portalUrl: 'https://www.stpi.in',
    portalName: 'STPI Portal / RBI EDPMS',
    summary: 'Statutory declaration certifying the export value of computer software, IT/ITeS services delivered via telecommunication or internet links, matched against inward remittances (e-BRC).',
    prerequisites: ['STPI Non-STP establishment registration', 'Export client master agreement and invoices', 'Foreign Inward Remittance Advices (FIRA)'],
    checklist: ['Monthly/Quarterly SOFTEX submission to STPI Director', 'Certification and transmission to Authorized Dealer (AD) Bank', 'Closure of open export bills on RBI EDPMS portal'],
    triggersSummary: 'Mandatory for SaaS and Software export businesses realizing revenue from foreign clients.',
  },
  {
    id: 'privacy_dpdp_gdpr',
    title: 'Digital Personal Data Protection (DPDP) Act & Global Privacy Framework',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Data Privacy',
    statutoryAuthority: 'Data Protection Board of India (DPBI) & Global DPAs',
    governingAct: 'Digital Personal Data Protection Act, 2023 / EU GDPR',
    obligationType: 'Conditional',
    turnaroundTime: '10–20 Business Days',
    turnaroundDays: 14,
    govtFee: 0,
    professionalFee: 15000,
    penaltyRisk: 'Statutory penalties up to ₹250 Crores under DPDP Act 2023 for significant data breaches or failure to prevent breach.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://meity.gov.in',
    portalName: 'Ministry of Electronics & Information Technology',
    summary: 'Institutional framework mandating itemized multi-lingual consent notices, designation of a Data Protection Officer (DPO), technical security measures, and data fiduciary grievance redressal mechanism.',
    prerequisites: ['Customer personal data inventory and flow architecture', 'Data processing agreements with cloud vendors (AWS, GCP, Stripe)'],
    checklist: ['Deployment of consent management mechanism on web applications', 'Drafting of statutory Privacy Notice under DPDP Section 5', 'Data breach response protocol and 72-hour notification plan'],
    triggersSummary: 'Mandatory for tech platforms, SaaS, fintech, and digital applications handling personal data.',
  },
  // --- ONLINE DELIVERY & E-COMMERCE SPECIFIC OBLIGATIONS ---
  {
    id: 'fssai_ecommerce_endorsement',
    title: 'FSSAI E-Commerce & Online Delivery License Endorsement',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Food Safety & E-Commerce',
    statutoryAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    governingAct: 'Food Safety and Standards (Licensing & Registration of Food Businesses) Amendment Regulations, 2020',
    obligationType: 'Mandatory',
    turnaroundTime: '5–10 Business Days',
    turnaroundDays: 7,
    govtFee: 3000,
    professionalFee: 2500,
    penaltyRisk: 'Immediate delisting from aggregator platforms; seizure of delivery consignments; fine up to ₹5,00,000.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://foscos.fssai.gov.in',
    portalName: 'FoSCoS E-Commerce Portal',
    summary: 'Mandatory statutory endorsement on FSSAI License authorizing e-commerce food operations, last-mile food delivery, and digital menu listing under Schedule 1 FSS regulations.',
    prerequisites: ['Primary FSSAI State/Central Manufacturing/Retail License', 'Hygiene rating compliance certificate', 'Delivery temperature maintenance protocol (cold chain)'],
    checklist: ['FoSCoS endorsement modification application', 'Food handler hygiene and medical fitness records', 'Delivery bag sanitization and tamper-evident packaging logs'],
    triggersSummary: 'Triggered when business operates in F&B / Food and engages in Online Delivery activity.',
  },
  {
    id: 'ecommerce_gst_tcs',
    title: 'E-Commerce GST TCS (Section 52) & Mandatory Operator Registration',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Indirect Taxation & E-Commerce',
    statutoryAuthority: 'Central Board of Indirect Taxes and Customs (CBIC) & GSTN',
    governingAct: 'Central Goods and Services Tax Act, 2017 (Section 24(ix) & Section 52)',
    obligationType: 'Mandatory',
    turnaroundTime: '3–5 Business Days',
    turnaroundDays: 4,
    govtFee: 0,
    professionalFee: 3000,
    penaltyRisk: 'Immediate withholding of payout disbursements by marketplaces; ₹10,000 or 100% tax penalty under Section 122(1)(vi).',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.gst.gov.in',
    portalName: 'GST Common Portal',
    summary: 'Under Section 24(ix) of CGST Act, the threshold exemption of ₹20L/₹40L is NOT available to e-commerce sellers; GST registration is mandatory from Day 1. Also covers 1% TCS reconciliation on Form GSTR-8.',
    prerequisites: ['Commercial warehouse / Registered office proof', 'PAN & Incorporation Certificate', 'Marketplace seller agreements (Swiggy, Zomato, Amazon, Blinkit)'],
    checklist: ['GST REG-01 registration with e-commerce declaration', 'Monthly GSTR-8 TCS credit reconciliation into Electronic Cash Ledger', 'E-way bill threshold integration for shipments exceeding ₹50,000'],
    triggersSummary: 'Mandatory for all businesses conducting online sales or deliveries via digital aggregators or D2C storefronts.',
  },
  {
    id: 'consumer_protection_ecommerce',
    title: 'Consumer Protection (E-Commerce) Rules 2020 Compliance',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Consumer Protection & Digital Retail',
    statutoryAuthority: 'Central Consumer Protection Authority (CCPA)',
    governingAct: 'Consumer Protection Act, 2019 / Consumer Protection (E-Commerce) Rules, 2020',
    obligationType: 'Mandatory',
    turnaroundTime: '5–7 Business Days',
    turnaroundDays: 5,
    govtFee: 0,
    professionalFee: 5000,
    penaltyRisk: 'CCPA class-action prosecution; penalty up to ₹10,00,000 for deceptive trade practices; suspension of digital storefront.',
    penaltySeverity: 'High',
    portalUrl: 'https://consumeraffairs.nic.in',
    portalName: 'National Consumer Helpline & CCPA',
    summary: 'Statutory compliance mandate requiring appointment of a Resident Grievance Officer, publishing ticket redressal timelines (48-hour acknowledgment, 1-month resolution), country of origin display, and non-discriminatory cancellation policies.',
    prerequisites: ['Designation of Grievance Redressal Officer with physical address in India', 'Website Terms of Service and Refund / Return Policy draft'],
    checklist: ['Publication of Grievance Officer name, email, and contact on website footer and checkout', 'Mandatory country-of-origin disclosure on all product listing pages', '48-hour automated complaint ticket acknowledgment system setup'],
    triggersSummary: 'Mandatory for all entities selling goods or services online, operating D2C storefronts, or conducting e-commerce deliveries.',
  },
  {
    id: 'customs_ad_code_icegate',
    title: 'Customs ICEGATE & Bank Authorized Dealer (AD) Code Registration',
    phase: 4,
    phaseLabel: 'Phase 4: Recurring Governance',
    category: 'Cross-Border Trade & Customs',
    statutoryAuthority: 'Directorate General of Systems and Data Management (CBIC)',
    governingAct: 'Customs Act, 1962 (Section 146 & 157)',
    obligationType: 'Mandatory',
    turnaroundTime: '3–6 Business Days',
    turnaroundDays: 4,
    govtFee: 0,
    professionalFee: 3500,
    penaltyRisk: 'Inability to generate electronic Shipping Bills or Bills of Entry; complete demurrage hold-up of freight shipments at sea/air ports.',
    penaltySeverity: 'Critical',
    portalUrl: 'https://www.icegate.gov.in',
    portalName: 'ICEGATE Indian Customs Electronic Gateway',
    summary: '14-digit Bank Authorized Dealer (AD) Code allotment from foreign exchange authorized bank, registered at specific customs ports (airports/seaports) to permit customs clearance and duty drawback processing.',
    prerequisites: ['Bank AD Code letter issued on bank letterhead with IFSC', 'DGFT Import Export Code (IEC) certificate', 'Class 3 DSC with Organization encryption token'],
    checklist: ['ICEGATE portal account creation', 'Port-wise AD Code registration submission with digital signature', 'Bank account validation for export incentives and electronic duty payment'],
    triggersSummary: 'Mandatory for all businesses importing raw materials or exporting physical commodities through sea, air, or land customs ports.',
  },
  {
    id: 'delivery_fleet_motor_guidelines',
    title: 'Commercial Motor Vehicle & Last-Mile Delivery Fleet Safety Norms',
    phase: 2,
    phaseLabel: 'Phase 2: Operational Clearances',
    category: 'Logistics & Fleet Safety',
    statutoryAuthority: 'Ministry of Road Transport and Highways (MoRTH) & State Transport Authority',
    governingAct: 'Motor Vehicles (Amendment) Act, 2019 & Motor Vehicle Aggregator Guidelines',
    obligationType: 'Conditional',
    turnaroundTime: '7–14 Business Days',
    turnaroundDays: 10,
    govtFee: 4500,
    professionalFee: 3500,
    penaltyRisk: 'Impounding of delivery vehicles; compounding fines up to ₹20,000 per violation for operating unauthorized commercial delivery fleets.',
    penaltySeverity: 'High',
    portalUrl: 'https://parivahan.gov.in',
    portalName: 'Parivahan Sewa Portal',
    summary: 'Statutory compliance for businesses operating an in-house fleet of delivery two-wheelers, electric delivery vehicles (EVs), or vans: commercial transport registration, mandatory third-party liability insurance, and delivery partner occupational safety norms.',
    prerequisites: ['Vehicle RC books with commercial/transport categorization', 'Valid commercial third-party insurance policies', 'Driver valid licenses and background check records'],
    checklist: ['Parivahan portal commercial fleet registration verification', 'Driver accident insurance coverage enrollment (minimum ₹5 Lakhs per driver)', 'GPS tracking and emergency SOS protocol implementation on delivery vehicles'],
    triggersSummary: 'Triggered when business engages in online delivery using its own dedicated fleet or direct delivery personnel.',
  },
];

export function getDocumentChecklistForItem(itemId: string): import('../types').DocumentChecklistItem[] {
  const commonDocs: import('../types').DocumentChecklistItem[] = [
    {
      id: `${itemId}_doc_pan`,
      name: 'Entity Permanent Account Number (PAN)',
      category: 'Identity Proof',
      isMandatory: true,
      description: 'Clear scanned copy of the corporate/entity or proprietor PAN card.',
      acceptedFormats: 'PDF, JPG (Max 5MB)',
    },
    {
      id: `${itemId}_doc_addr`,
      name: 'Registered Office Premise Proof (Lease Deed / Ownership Deed)',
      category: 'Address Proof',
      isMandatory: true,
      description: 'Registered rent agreement or property deed along with Landlord No-Objection Certificate (NOC).',
      acceptedFormats: 'PDF (Max 10MB)',
    },
    {
      id: `${itemId}_doc_util`,
      name: 'Recent Electricity / Utility Bill (< 60 Days Old)',
      category: 'Address Proof',
      isMandatory: true,
      description: 'Municipal water, electricity, or gas bill showing the registered address clearly.',
      acceptedFormats: 'PDF, JPG',
    },
  ];

  switch (itemId) {
    case 'mca_dsc':
      return [
        {
          id: 'dsc_pan',
          name: 'Director PAN Card Copy',
          category: 'Identity Proof',
          isMandatory: true,
          description: 'Self-attested PAN card of prospective Director or Designated Partner.',
          acceptedFormats: 'PDF, JPG',
        },
        {
          id: 'dsc_aadhaar',
          name: 'Director Aadhaar Card with OTP Link',
          category: 'Identity Proof',
          isMandatory: true,
          description: 'Aadhaar card linked to active mobile phone for UIDAI OTP e-KYC verification.',
          acceptedFormats: 'PDF, JPG',
        },
        {
          id: 'dsc_photo',
          name: 'Passport-Size Digital Photograph',
          category: 'Identity Proof',
          isMandatory: true,
          description: 'Recent white background passport photograph for video KYC authentication.',
          acceptedFormats: 'JPG, PNG',
        },
      ];

    case 'mca_name_approval':
      return [
        {
          id: 'name_obj',
          name: 'Draft Main Business Objects Summary',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Detailed description of proposed business activities (MoA Clause III(a)).',
          acceptedFormats: 'PDF, DOCX',
        },
        {
          id: 'name_tm',
          name: 'IPIndia Trademark Clearance Search Report',
          category: 'Operational & Technical',
          isMandatory: false,
          description: 'Search report showing no identical phonetics or wordmarks in relevant Nice classes.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'mca_incorporation_spice':
      return [
        ...commonDocs,
        {
          id: 'spice_moa_aoa',
          name: 'Draft Electronic MoA & AoA (e-MoA Form INC-33 & e-AoA Form INC-34)',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Memorandum and Articles of Association executed digitally with Class 3 DSC.',
          acceptedFormats: 'PDF',
        },
        {
          id: 'spice_dir2',
          name: 'Consent to Act as Director (Form DIR-2)',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Signed declaration from each director confirming willingness to hold office.',
          acceptedFormats: 'PDF',
        },
        {
          id: 'spice_inc8',
          name: 'Practicing Professional Declaration (Form INC-8)',
          category: 'Financial & Tax',
          isMandatory: true,
          description: 'Attestation by practicing Chartered Accountant or Company Secretary.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'fssai_license':
    case 'fssai_ecommerce_endorsement':
      return [
        ...commonDocs,
        {
          id: 'fssai_layout',
          name: 'Kitchen / Operational Blueprint & Equipment Layout Plan',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Dimensioned floor plan showing food handling zones, storage, and handwash stations.',
          acceptedFormats: 'PDF, DWG',
        },
        {
          id: 'fssai_water',
          name: 'Potable Water Chemical & Bacteriological Test Report',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Water potability report issued by an NABL-accredited testing laboratory within 6 months.',
          acceptedFormats: 'PDF',
        },
        {
          id: 'fssai_medical',
          name: 'Medical Fitness Certificates for Food Handlers (Form IX)',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Fitness and inoculation certificates signed by a registered medical practitioner.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'ecommerce_gst_tcs':
    case 'tax_gst_registration':
      return [
        ...commonDocs,
        {
          id: 'gst_bank',
          name: 'Bank Current Account Cancelled Cheque / Statement',
          category: 'Financial & Tax',
          isMandatory: true,
          description: 'Bank cheque showing account name, IFSC, and business account number.',
          acceptedFormats: 'PDF, JPG',
        },
        {
          id: 'gst_auth_letter',
          name: 'Board Resolution / Letter of Authorization for GST Primary Signatory',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Formal resolution authorizing appointed officer to sign GST returns.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'trade_iec_dgft':
    case 'customs_ad_code_icegate':
      return [
        ...commonDocs,
        {
          id: 'iec_bank_cert',
          name: 'Bank Authorized Dealer (AD) Code Letter with IFSC',
          category: 'Financial & Tax',
          isMandatory: true,
          description: 'Official letter from scheduled commercial bank confirming 14-digit AD code.',
          acceptedFormats: 'PDF',
        },
        {
          id: 'iec_pan_cert',
          name: 'DGFT IEC Digital Certificate',
          category: 'Identity Proof',
          isMandatory: true,
          description: '10-digit Import Export Code issued by Directorate General of Foreign Trade.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'labour_esic':
    case 'labour_epfo':
      return [
        ...commonDocs,
        {
          id: 'labour_employee_master',
          name: 'Complete Employee Master Data & Salary Structure Sheet',
          category: 'Financial & Tax',
          isMandatory: true,
          description: 'Roster containing Employee Names, Aadhaar numbers, PAN, Gross Wages, Basic + DA, and date of joining.',
          acceptedFormats: 'XLSX, CSV, PDF',
        },
        {
          id: 'labour_dsc',
          name: 'Digital Signature Certificate for Electronic Return Signing',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Class 3 DSC registered on EPFO Unified Portal / Shram Suvidha.',
          acceptedFormats: 'Hardware Token Driver Confirmation',
        },
      ];

    case 'posh_internal_committee':
      return [
        {
          id: 'posh_policy',
          name: 'Board-Approved POSH Workplace Anti-Harassment Policy',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Comprehensive policy detailing prevention, inquiry procedure, and conciliation norms.',
          acceptedFormats: 'PDF, DOCX',
        },
        {
          id: 'posh_ic_order',
          name: 'Internal Committee (IC) Formal Constitution Office Order',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Appointment letters designating Presiding Officer, 2 internal employees, and 1 independent external NGO member.',
          acceptedFormats: 'PDF',
        },
      ];

    case 'consumer_protection_ecommerce':
      return [
        {
          id: 'cp_grievance_order',
          name: 'Nodal Officer & Grievance Redressal Officer Appointment Letter',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Formal corporate appointment defining officer name, direct phone, and escalation email.',
          acceptedFormats: 'PDF',
        },
        {
          id: 'cp_terms',
          name: 'Digital Consumer Terms of Service & Cancellation / Return Policy Draft',
          category: 'Entity Charter',
          isMandatory: true,
          description: 'Clear consumer policy specifying refund windows, delivery timelines, and country-of-origin labels.',
          acceptedFormats: 'PDF, DOCX',
        },
      ];

    default:
      return [
        ...commonDocs,
        {
          id: `${itemId}_spec_proof`,
          name: 'Statutory Prescribed Application Form & Signatures',
          category: 'Operational & Technical',
          isMandatory: true,
          description: 'Completed statutory form with required declarations and director seals.',
          acceptedFormats: 'PDF',
        },
      ];
  }
}

